DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user (
  id INTEGER PRIMARY KEY NOT NULL UNIQUE,
  account TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL
);

CREATE TABLE file (
  id INTEGER PRIMARY KEY NOT NULL UNIQUE,
  author_id INTEGER NOT NULL,
  upload_time INTEGER NOT NULL,
  file_name TEXT NOT NULL
);
